In [5]:
import numpy as np
import	matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from	sklearn.model_selection import train_test_split

scaler = MinMaxScaler()
train = pd.read_csv('train.csv')
train.set_index('ID',	inplace=True)



#Cambio a Nans
problema = ['Yhlr', 'Jhlr', 'Hhlr', 'Khlr']

train[problema] = train[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
imputer = KNNImputer(missing_values=np.nan, n_neighbors=5, weights='distance',)

train_estrella = train[train['Hclass'] == 0]
train_galaxia = train[train['Hclass'] == 1]
train_qso = train[train['Hclass'] == 2]

train_estrella[problema] = imputer.fit_transform(train_estrella[problema])
train_galaxia[problema] = imputer.fit_transform(train_galaxia[problema])
train_qso[problema] = imputer.fit_transform(train_qso[problema])

train = pd.concat([train_estrella, train_galaxia, train_qso])
train = train.sample(frac=1, random_state=4)



#Magnitudes, para armar colores
H = train.loc[:,'Hmag']
J	= train.loc[:,'Jmag']
U =	train.loc[:,'umag']
G =	train.loc[:,'gmag']
r = train.loc[:,'rmag']
i = train.loc[:,'imag']
z = train.loc[:,'zmag']
Y = train.loc[:,'Ymag']
K = train.loc[:,'Kmag']
W1 =	train.loc[:,'W1mag']
W2 =	train.loc[:,'W2mag']



#Radios donde se encierra la mitad de la luz

Y_r =	train.loc[:,'Yhlr']
J_r =	train.loc[:,'Jhlr']
H_r =	train.loc[:,'Hhlr']
K_r =	train.loc[:,'Khlr']





#Magnitud en apertura fija de 3''

U3 =	train.loc[:,'u3mag']
G3 =	train.loc[:,'g3mag']
r3 =	train.loc[:,'r3mag']
i3 =	train.loc[:,'i3mag']
Z3	=	train.loc[:,'Z3mag']
Y3	=	train.loc[:,'Y3mag']
J3	=	train.loc[:,'J3mag']
H3	=	train.loc[:,'H3mag']
K3	=	train.loc[:,'K3mag']





#Coordenadas

ra = train.loc[:,'RAdeg']
dec = train.loc[:,'DEdeg']

#Clases para entrenar

clase	= train.loc[:,'Hclass'] #0: Estrella, 1: Galaxia, 2: QSO






# Agregar columnas U-G, G-R, i-z, J3/J_r y Y3/Y_r

U_G=	U - G
G_R=	G - r
i_z=	i - z
J3_J_r=	J3 / J_r
Y3_Y_r=	Y3 / Y_r
W2_W1=	W2 - W1
H_K=	H - K
H_J=	H - J
J_K=	J - K
Y_J=	Y - J
Y_K=	Y - K
J_H=	J - H
K_H=	K - H
K_J=	K - J
Y_H=	Y - H
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
J_W2=	J - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1




train['Hmag'] = H
train['Jmag'] = J
train['umag'] = U
train['gmag'] = G
train['rmag'] = r
train['imag'] = i
train['zmag'] = z
train['Ymag'] = Y
train['Kmag'] = K
train['W1mag'] = W1
train['W2mag'] = W2

train['Yhlr'] = Y_r
train['Jhlr'] = J_r
train['Hhlr'] = H_r
train['Khlr'] = K_r

train['u3mag'] = U3
train['g3mag'] = G3
train['r3mag'] = r3
train['i3mag'] = i3
train['Z3mag'] = Z3
train['Y3mag'] = Y3
train['J3mag'] = J3
train['H3mag'] = H3
train['K3mag'] = K3

train['U-G'] = U_G
train['G-R'] = G_R
train['i-z'] = i_z
train['J3/J_r'] = J3_J_r
train['Y3/Y_r'] = Y3_Y_r
train['W2-W1'] = W2_W1
train['H-K'] = H_K
train['H-J'] = H_J
train['J-K'] = J_K
train['Y-J'] = Y_J
train['Y-K'] = Y_K
train['J-H'] = J_H
train['K-H'] = K_H
train['K-J'] = K_J
train['Y-H'] = Y_H
train['H-W1'] = H_W1
train['J-W1'] = J_W1
train['K-W1'] = K_W1
train['Y-W1'] = Y_W1
train['H-W2'] = H_W2
train['K-W2'] = K_W2
train['Y-W2'] = Y_W2
train['J-W2'] = J_W2


df_train, df_test = train_test_split(train, test_size=0.3, random_state=42)

df_train2 = df_train.drop(columns=['Hclass'])
df_test2 = df_test.drop(columns=['Hclass'])

scaler.fit(df_train2)
df_train = pd.DataFrame(scaler.transform(df_train2), columns=df_train2.columns, index=df_train2.index)
df_test	= pd.DataFrame(scaler.transform(df_test2), columns=df_test2.columns, index=df_test2.index)

df_train2['Hclass'] = train['Hclass']
df_test2['Hclass'] = train['Hclass']


/tmp/ipykernel_4467/947898190.py:17: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  train[problema] = train[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
/tmp/ipykernel_4467/947898190.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_estrella[problema] = imputer.fit_transform(train_estrella[problema])
/tmp/ipykernel_4467/947898190.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_galaxia[problema] = imputer.fit_transform(train_galaxia[pr

H = (H-min(H))/(max(H)-min(H))
J = (J-min(J))/(max(J)-min(J))
U = (U-min(U))/(max(U)-min(U))
G = (G-min(G))/(max(G)-min(G))
r = (r-min(r))/(max(r)-min(r))
i = (i-min(i))/(max(i)-min(i))
z = (z-min(z))/(max(z)-min(z))
Y = (Y-min(Y))/(max(Y)-min(Y))
K = (K-min(K))/(max(K)-min(K))
W1 = (W1-min(W1))/(max(W1)-min(W1))
W2 = (W2-min(W2))/(max(W2)-min(W2))

Y_r	= (Y_r-min(Y_r))/(max(Y_r)-min(Y_r))
J_r	= (J_r-min(J_r))/(max(J_r)-min(J_r))
H_r	= (H_r-min(H_r))/(max(H_r)-min(H_r))
K_r	= (K_r-min(K_r))/(max(K_r)-min(K_r))

U3	= (U3-min(U3))/(max(U3)-min(U3))
G3	= (G3-min(G3))/(max(G3)-min(G3))
r3	= (r3-min(r3))/(max(r3)-min(r3))
i3	= (i3-min(i3))/(max(i3)-min(i3))
Z3	= (Z3-min(Z3))/(max(Z3)-min(Z3))
Y3	= (Y3-min(Y3))/(max(Y3)-min(Y3))
J3	= (J3-min(J3))/(max(J3)-min(J3))
H3	= (H3-min(H3))/(max(H3)-min(H3))
K3	= (K3-min(K3))/(max(K3)-min(K3))




U_G = (U_G-min(U_G))/(max(U_G)-min(U_G))
G_R = (G_R-min(G_R))/(max(G_R)-min(G_R))
i_z = (i_z-min(i_z))/(max(i_z)-min(i_z))
J3_J_r = (J3_J_r-min(J3_J_r))/(max(J3_J_r)-min(J3_J_r))
Y3_Y_r = (Y3_Y_r-min(Y3_Y_r))/(max(Y3_Y_r)-min(Y3_Y_r))
W2_W1 = (W2_W1-min(W2_W1))/(max(W2_W1)-min(W2_W1))
H_K = (H_K-min(H_K))/(max(H_K)-min(H_K))
H_J = (H_J-min(H_J))/(max(H_J)-min(H_J))
J_K = (J_K-min(J_K))/(max(J_K)-min(J_K))
Y_J = (Y_J-min(Y_J))/(max(Y_J)-min(Y_J))
Y_K = (Y_K-min(Y_K))/(max(Y_K)-min(Y_K))
J_H = (J_H-min(J_H))/(max(J_H)-min(J_H))
K_H = (K_H-min(K_H))/(max(K_H)-min(K_H))
K_J = (K_J-min(K_J))/(max(K_J)-min(K_J))
Y_H = (Y_H-min(Y_H))/(max(Y_H)-min(Y_H))
H_W1 = (H_W1-min(H_W1))/(max(H_W1)-min(H_W1))
J_W1 = (J_W1-min(J_W1))/(max(J_W1)-min(J_W1))
K_W1 = (K_W1-min(K_W1))/(max(K_W1)-min(K_W1))
Y_W1 = (Y_W1-min(Y_W1))/(max(Y_W1)-min(Y_W1))
H_W2 = (H_W2-min(H_W2))/(max(H_W2)-min(H_W2))
K_W2 = (K_W2-min(K_W2))/(max(K_W2)-min(K_W2))
Y_W2 = (Y_W2-min(Y_W2))/(max(Y_W2)-min(Y_W2))
H_W1 = (H_W1-min(H_W1))/(max(H_W1)-min(H_W1))
J_W2	= (J_W2-min(J_W2))/(max(J_W2)-min(J_W2))


In [49]:
df_train.describe()

RAdeg         DEdeg        Hclass          umag          gmag  \
count  3.651400e+04  36514.000000  36514.000000  36514.000000  36514.000000   
mean   6.444338e-01      0.593986      0.463658      0.385803      0.320855   
std    3.470191e-01      0.247951      0.244753      0.121706      0.095695   
min   -8.363298e-07      0.000000      0.000000      0.000000      0.000000   
25%    5.259360e-01      0.433033      0.500000      0.286847      0.242282   
50%    7.718481e-01      0.646929      0.500000      0.383062      0.318206   
75%    9.172339e-01      0.774089      0.500000      0.478261      0.400955   
max    1.000022e+00      1.000000      1.000000      1.000000      1.000000   

               rmag          imag          zmag          Ymag          Jmag  \
count  36514.000000  36514.000000  36514.000000  36514.000000  36514.000000   
mean       0.551536      0.291663      0.579436      0.589619      0.592093   
std        0.149027      0.071780      0.137167      0.141757      0.137817   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.432652      0.235223      0.470585      0.476612      0.481785   
50%        0.544791      0.291116      0.582071      0.593687      0.596036   
75%        0.667448      0.344601      0.682834      0.694084      0.691555   
max        1.009704      1.000000      1.000000      1.000000      1.000000   

       ...           K-J           Y-H          H-W1          J-W1  \
count  ...  36514.000000  36514.000000  36514.000000  36514.000000   
mean   ...      0.654917      0.391452      0.439452      0.349282   
std    ...      0.066566      0.066713      0.123983      0.144575   
min    ...      0.000000     -0.020718      0.000000     -0.056477   
25%    ...      0.606586      0.358726      0.336815      0.238940   
50%    ...      0.642509      0.400237      0.432365      0.350709   
75%    ...      0.690299      0.434585      0.538072      0.468939   
max    ...      1.068010      1.000000      1.000000      1.000000   

               K-W1          Y-W1          H-W2          K-W2          Y-W2  \
count  36514.000000  36514.000000  36514.000000  36514.000000  36514.000000   
mean       0.334180      0.428592      0.387700      0.373756      0.437603   
std        0.102630      0.149660      0.134825      0.118116      0.137968   
min       -0.047969     -0.062875      0.000000      0.000000     -0.038428   
25%        0.248211      0.321947      0.290568      0.291977      0.345008   
50%        0.305335      0.436298      0.383552      0.351388      0.452873   
75%        0.410401      0.550750      0.460586      0.421399      0.530996   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

               J-W2  
count  36514.000000  
mean       0.384657  
std        0.142583  
min       -0.044506  
25%        0.285717  
50%        0.390843  
75%        0.476343  
max        1.000000  

[8 rows x 50 columns]

In [6]:
df_train2.isna().sum()

RAdeg     0
DEdeg     0
umag      0
gmag      0
rmag      0
imag      0
zmag      0
Ymag      0
Jmag      0
Hmag      0
Kmag      0
W1mag     0
W2mag     0
u3mag     0
g3mag     0
r3mag     0
i3mag     0
Z3mag     0
Y3mag     0
J3mag     0
H3mag     0
K3mag     0
Yhlr      0
Jhlr      0
Hhlr      0
Khlr      0
U-G       0
G-R       0
i-z       0
J3/J_r    0
Y3/Y_r    0
W2-W1     0
H-K       0
H-J       0
J-K       0
Y-J       0
Y-K       0
J-H       0
K-H       0
K-J       0
Y-H       0
H-W1      0
J-W1      0
K-W1      0
Y-W1      0
H-W2      0
K-W2      0
Y-W2      0
J-W2      0
Hclass    0
dtype: int64

In [32]:
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import f1_score, confusion_matrix, classification_report


features = ['U-G', 'G-R','i-z', 'Hmag','Jmag','umag','gmag','rmag','imag','zmag','Ymag','Kmag','W1mag','W2mag','u3mag','g3mag','r3mag','i3mag','Z3mag','Y3mag','J3mag','H3mag',
            'K3mag', 'J3/J_r', 'Y3/Y_r', 'Yhlr', 'Jhlr', 'Hhlr', 'Khlr',
            'H-K', 'H-J', 'J-K', 'Y-J', 'Y-K', 'J-H', 'K-H', 'K-J', 'Y-H', 'H-W1','J-W1','K-W1','Y-W1','H-W2','J-W2','K-W2',
            'Y-W2','H-W1','J-W1','K-W1','Y-W1','H-W2','J-W2','K-W2','Y-W2','H-W1','J-W1','K-W1','Y-W1','H-W2','J-W2','K-W2',
            'Y-W2','H-W1','J-W1'] 




X_train = df_train2[features]
Y_train	= df_train2['Hclass']
X_test	= df_test2[features]
Y_test	= df_test2['Hclass']

clf = MLPClassifier(hidden_layer_sizes=(200,100,50,25), max_iter=500, alpha=0.0001, activation='tanh',  random_state=21,
                    learning_rate='invscaling', tol=0.0001)

In [33]:
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))
print(f1_score(Y_test, Y_pred, average='weighted'))

[[1741   19    5]
 [   7 8212   25]
 [   2   99  845]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1765
           1       0.99      1.00      0.99      8244
           2       0.97      0.89      0.93       946

    accuracy                           0.99     10955
   macro avg       0.98      0.96      0.97     10955
weighted avg       0.99      0.99      0.99     10955

0.9854646220582727


In [34]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, X_train, Y_train, cv=5, scoring='f1_weighted', n_jobs=-1)
print(scores)

[0.98095575 0.98454134 0.98470563 0.98576002 0.98169595]


In [36]:
test = pd.read_csv('test.csv')
test.set_index('ID', inplace=True)




#Cambio a Nans
problema = ['Yhlr', 'Jhlr', 'Hhlr', 'Khlr']

test[problema] = test[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)

#Los transformo con la mediana de los valores pues sino los nans dan error
test[problema] = imputer.fit_transform(test[problema])



#Magnitudes, para armar colores
H = test.loc[:,'Hmag']
J	= test.loc[:,'Jmag']
U =	test.loc[:,'umag']
G =	test.loc[:,'gmag']
r = test.loc[:,'rmag']
i = test.loc[:,'imag']
z = test.loc[:,'zmag']
Y = test.loc[:,'Ymag']
K = test.loc[:,'Kmag']
W1 =	test.loc[:,'W1mag']
W2 =	test.loc[:,'W2mag']



#Radios donde se encierra la mitad de la luz

Y_r =	test.loc[:,'Yhlr']
J_r =	test.loc[:,'Jhlr']
H_r =	test.loc[:,'Hhlr']
K_r =	test.loc[:,'Khlr']





#Magnitud en apertura fija de 3''

U3 =	test.loc[:,'u3mag']
G3 =	test.loc[:,'g3mag']
r3 =	test.loc[:,'r3mag']
i3 =	test.loc[:,'i3mag']
Z3	=	test.loc[:,'Z3mag']
Y3	=	test.loc[:,'Y3mag']
J3	=	test.loc[:,'J3mag']
H3	=	test.loc[:,'H3mag']
K3	=	test.loc[:,'K3mag']





#Coordenadas

ra = test.loc[:,'RAdeg']
dec = test.loc[:,'DEdeg']

#Clases para entrenar

clase	= train.loc[:,'Hclass'] #0: Estrella, 1: Galaxia, 2: QSO






# Agregar columnas U-G, G-R, i-z, J3/J_r y Y3/Y_r

U_G=	U - G
G_R=	G - r
i_z=	i - z
J3_J_r=	J3 / J_r
Y3_Y_r=	Y3 / Y_r
W2_W1=	W2 - W1
H_K=	H - K
H_J=	H - J
J_K=	J - K
Y_J=	Y - J
Y_K=	Y - K
J_H=	J - H
K_H=	K - H
K_J=	K - J
Y_H=	Y - H
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
J_W2=	J - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1
J_W1=	J - W1
K_W1=	K - W1
Y_W1=	Y - W1
H_W2=	H - W2
K_W2=	K - W2
Y_W2=	Y - W2
H_W1=	H - W1

test['Hmag'] = H
test['Jmag'] = J
test['umag'] = U
test['gmag'] = G
test['rmag'] = r
test['imag'] = i
test['zmag'] = z
test['Ymag'] = Y
test['Kmag'] = K
test['W1mag'] = W1
test['W2mag'] = W2

test['Yhlr'] = Y_r
test['Jhlr'] = J_r
test['Hhlr'] = H_r
test['Khlr'] = K_r

test['u3mag'] = U3
test['g3mag'] = G3
test['r3mag'] = r3
test['i3mag'] = i3
test['Z3mag'] = Z3
test['Y3mag'] = Y3
test['J3mag'] = J3
test['H3mag'] = H3
test['K3mag'] = K3

test['U-G'] = U_G
test['G-R'] = G_R
test['i-z'] = i_z
test['J3/J_r'] = J3_J_r
test['Y3/Y_r'] = Y3_Y_r
test['W2-W1'] = W2_W1
test['H-K'] = H_K
test['H-J'] = H_J
test['J-K'] = J_K
test['Y-J'] = Y_J
test['Y-K'] = Y_K
test['J-H'] = J_H
test['K-H'] = K_H
test['K-J'] = K_J
test['Y-H'] = Y_H
test['H-W1'] = H_W1
test['J-W1'] = J_W1
test['K-W1'] = K_W1
test['Y-W1'] = Y_W1
test['H-W2'] = H_W2
test['K-W2'] = K_W2
test['Y-W2'] = Y_W2
test['J-W2'] = J_W2
#Elegir sólo las columnas que se usaron para entrenar


test = pd.DataFrame(scaler.transform(test), columns=test.columns, index=test.index)

X_test_final = test[features]



predictions = clf.predict(X_test_final)

test['Hclass'] = predictions

test.loc[:, ['Hclass']].to_csv('submit17.csv', index=True)

/tmp/ipykernel_4467/2839525992.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  test[problema] = test[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
