In [ ]:
import numpy as np
import	matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import KNNImputer


train = pd.read_csv('train.csv')
train.set_index('ID',	inplace=True)

#Cambio a Nans
problema = ['Yhlr', 'Jhlr', 'Hhlr', 'Khlr']

train[problema] = train[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
imputer = KNNImputer(missing_values=np.nan, n_neighbors=5, weights='distance',)

train_estrella = train[train['Hclass'] == 0]
train_galaxia = train[train['Hclass'] == 1]
train_qso = train[train['Hclass'] == 2]

train_estrella[problema] = imputer.fit_transform(train_estrella[problema])
train_galaxia[problema] = imputer.fit_transform(train_galaxia[problema])
train_qso[problema] = imputer.fit_transform(train_qso[problema])

train = pd.concat([train_estrella, train_galaxia, train_qso])
train = train.sample(frac=1, random_state=4)





#Magnitudes, para armar colores
H = train.loc[:,'Hmag']
J	= train.loc[:,'Jmag']
U =	train.loc[:,'umag']
G =	train.loc[:,'gmag']
r = train.loc[:,'rmag']
i = train.loc[:,'imag']
z = train.loc[:,'zmag']
Y = train.loc[:,'Ymag']
K = train.loc[:,'Kmag']
W1 =	train.loc[:,'W1mag']
W2 =	train.loc[:,'W2mag']

#Radios donde se encierra la mitad de la luz

Y_r =	train.loc[:,'Yhlr']
J_r =	train.loc[:,'Jhlr']
H_r =	train.loc[:,'Hhlr']
K_r =	train.loc[:,'Khlr']

#Magnitud en apertura fija de 3''

U3 =	train.loc[:,'u3mag']
G3 =	train.loc[:,'g3mag']
r3 =	train.loc[:,'r3mag']
i3 =	train.loc[:,'i3mag']
Z3	=	train.loc[:,'Z3mag']
Y3	=	train.loc[:,'Y3mag']
J3	=	train.loc[:,'J3mag']
H3	=	train.loc[:,'H3mag']
K3	=	train.loc[:,'K3mag']

#Coordenadas

ra = train.loc[:,'RAdeg']
dec = train.loc[:,'DEdeg']

#Clases para entrenar

clase	= train.loc[:,'Hclass'] #0: Estrella, 1: Galaxia, 2: QSO






# Agregar columnas U-G, G-R, i-z, J3/J_r y Y3/Y_r
train['U-G'] = U - G
train['G-R'] = G - r
train['i-z'] = i - z
train['J3/J_r'] = J3 / J_r
train['Y3/Y_r'] = Y3 / Y_r
train['W2-W1'] = W2 - W1
train['H-K'] = H - K
train['H-J'] = H - J
train['J-K'] = J - K
train['Y-J'] = Y - J
train['Y-K'] = Y - K
train['J-H'] = J - H
train['K-H'] = K - H
train['K-J'] = K - J
train['Y-H'] = Y - H
train['H-W1'] = H - W1
train['J-W1'] = J - W1
train['K-W1'] = K - W1
train['Y-W1'] = Y - W1
train['H-W2'] = H - W2
train['J-W2'] = J - W2

/tmp/ipykernel_4782/2207524605.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  train[problema] = train[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
/tmp/ipykernel_4782/2207524605.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_estrella[problema] = imputer.fit_transform(train_estrella[problema])
/tmp/ipykernel_4782/2207524605.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_galaxia[problema] = imputer.fit_transform(train_galaxia

In [8]:
train.describe()

RAdeg         DEdeg        Hclass          umag          gmag  \
count  36514.000000  36514.000000  36514.000000  36514.000000  36514.000000   
mean     157.413606     -0.926899      0.927316     21.326973     19.904223   
std       66.388946      2.411410      0.489506      2.345232      2.289705   
min       34.125470     -6.703610      0.000000     13.892700     12.227100   
25%      134.743538     -2.492215      1.000000     19.420125     18.024200   
50%      181.789490     -0.412005      1.000000     21.274150     19.840850   
75%      209.603552      0.824670      1.000000     23.108600     21.820800   
max      225.441880      3.021730      2.000000     33.162300     36.154200   

               rmag          imag          zmag          Ymag          Jmag  \
count  36514.000000  36514.000000  36514.000000  36514.000000  36514.000000   
mean      18.887562     18.323593     18.201334     18.022149     17.879179   
std        2.024082      1.809982      1.721633      1.670744      1.618812   
min       11.396600     10.969100     10.928600     11.072900     10.924400   
25%       17.272875     16.900425     16.835100     16.690250     16.583500   
50%       18.795950     18.309800     18.234400     18.070100     17.925500   
75%       20.461875     19.658450     19.499125     19.253375     19.047475   
max       25.110400     36.184800     23.480000     22.858900     22.670500   

       ...         K3mag          Yhlr          Jhlr          Hhlr  \
count  ...  36514.000000  36514.000000  36514.000000  36514.000000   
mean   ...     17.825652      1.218327      1.079822      1.055483   
std    ...      1.218845      0.732733      0.647390      0.668833   
min    ...     13.105300      0.341090      0.232720      0.272110   
25%    ...     16.873950      0.751437      0.691050      0.675780   
50%    ...     17.902300      1.049985      0.895320      0.865005   
75%    ...     18.628375      1.433863      1.286220      1.257345   
max    ...     21.743800     29.585910     23.569090     28.524720   

               Khlr           U-G           G-R           i-z        J3/J_r  \
count  36514.000000  36514.000000  36514.000000  36514.000000  36514.000000   
mean       1.002750      1.422750      1.016661      0.122259     20.809220   
std        0.623073      0.862094      0.555416      0.284985      8.596869   
min        0.305210    -14.195100     -1.542000     -3.752900      0.755574   
25%        0.641770      0.884300      0.598500     -0.019700     13.375563   
50%        0.838285      1.378100      0.989550      0.110750     21.193102   
75%        1.193087      1.890275      1.467300      0.260400     26.490218   
max       29.329210     12.430800     15.453400     19.466800     94.966483   

             Y3/Y_r  
count  36514.000000  
mean      18.675111  
std        7.781943  
min        0.531378  
25%       12.181167  
50%       18.042409  
75%       24.290939  
max       62.810988  

[8 rows x 32 columns]

In [46]:
from sklearn.ensemble import RandomForestClassifier
from	sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, confusion_matrix, classification_report


features = ['U-G', 'G-R','i-z', 'Hmag','Jmag','umag','gmag','rmag','imag','zmag','Ymag','Kmag','W1mag','W2mag','u3mag','g3mag','r3mag','i3mag','Z3mag','Y3mag','J3mag','H3mag',
            'K3mag', 'J3/J_r', 'Y3/Y_r', 'Yhlr', 'Jhlr', 'Hhlr', 'Khlr',
            'H-K', 'H-J', 'J-K', 'Y-J', 'Y-K', 'J-H', 'K-H', 'K-J', 'Y-H', 'H-W1', 'J-W1', 'K-W1',] 



df_train, df_test = train_test_split(train, test_size=0.3, random_state=42)
X_train = df_train[features]
Y_train	= df_train['Hclass']
X_test	= df_test[features]
Y_test	= df_test['Hclass']

clf = RandomForestClassifier(n_estimators=150, random_state=42,min_samples_split=15, min_samples_leaf=3,
                             max_depth=15, criterion='entropy',bootstrap=True, n_jobs=-1)

In [47]:
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))
print(f1_score(Y_test, Y_pred, average='weighted'))

[[1740   20    5]
 [   5 8203   36]
 [   2   85  859]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1765
           1       0.99      1.00      0.99      8244
           2       0.95      0.91      0.93       946

    accuracy                           0.99     10955
   macro avg       0.98      0.96      0.97     10955
weighted avg       0.99      0.99      0.99     10955

0.9859064772103936


In [48]:
pd.DataFrame(clf.feature_importances_*100, index=features)

0
U-G      0.989942
G-R      4.924524
i-z      0.216043
Hmag     0.263035
Jmag     0.508516
umag     1.787275
gmag     2.053667
rmag     0.510655
imag     0.455537
zmag     0.660305
Ymag     0.546130
Kmag     0.195477
W1mag    0.247484
W2mag    0.757857
u3mag    1.437681
g3mag    1.662808
r3mag    0.710240
i3mag    0.906835
Z3mag    0.785482
Y3mag    1.239317
J3mag    1.241099
H3mag    0.325970
K3mag    0.158452
J3/J_r   2.673592
Y3/Y_r   1.961399
Yhlr    13.269919
Jhlr    10.605102
Hhlr     6.325535
Khlr     7.862047
H-K      2.037790
H-J      0.451349
J-K      3.904415
Y-J      0.327064
Y-K      3.259027
J-H      1.176780
K-H      1.601764
K-J      5.824787
Y-H      0.851823
H-W1     4.590780
J-W1     8.249170
K-W1     2.443328

In [49]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, X_train, Y_train, cv=5, scoring='f1_weighted', n_jobs=-1)
print(scores)

[0.98270127 0.98571049 0.98721182 0.98778648 0.98373997]


In [50]:
test = pd.read_csv('test.csv')
test.set_index('ID', inplace=True)




#Cambio a Nans
problema = ['Yhlr', 'Jhlr', 'Hhlr', 'Khlr']

test[problema] = test[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)

#Los transformo con la mediana de los valores pues sino los nans dan error
test[problema] = imputer.fit_transform(test[problema])




# Magnitudes, para armar colores
H = test.loc[:, 'Hmag']
J = test.loc[:, 'Jmag']
U = test.loc[:, 'umag']
G = test.loc[:, 'gmag']
r = test.loc[:, 'rmag']
i = test.loc[:, 'imag']
z = test.loc[:, 'zmag']
Y = test.loc[:, 'Ymag']
K = test.loc[:, 'Kmag']
W1 = test.loc[:, 'W1mag']
W2 = test.loc[:, 'W2mag']

# Radios donde se encierra la mitad de la luz
Y_r = test.loc[:, 'Yhlr']
J_r = test.loc[:, 'Jhlr']
H_r = test.loc[:, 'Hhlr']
K_r = test.loc[:, 'Khlr']

# Magnitud en apertura fija de 3''
U3 = test.loc[:, 'u3mag']
G3 = test.loc[:, 'g3mag']
r3 = test.loc[:, 'r3mag']
i3 = test.loc[:, 'i3mag']
Z3 = test.loc[:, 'Z3mag']
Y3 = test.loc[:, 'Y3mag']
J3 = test.loc[:, 'J3mag']
H3 = test.loc[:, 'H3mag']
K3 = test.loc[:, 'K3mag']

# Coordenadas
ra = test.loc[:, 'RAdeg']
dec = test.loc[:, 'DEdeg']

#NO TIRO LOS NANS PORQUE SINO NO ES VÁLIDO EN KAGGLE

# Agregar columnas U-G, G-R, J3/J_r y Y3/Y_r
test['U-G'] = U - G
test['G-R'] = G - r
test['J3/J_r'] = J3 / J_r
test['Y3/Y_r'] = Y3 / Y_r
test['i-z'] = i - z
test['W2-W1'] = W2 - W1
test['H-K'] = H - K
test['H-J'] = H - J
test['J-K'] = J - K
test['Y-J'] = Y - J
test['Y-K'] = Y - K
test['J-H'] = J - H
test['K-H'] = K - H
test['K-J'] = K - J
test['Y-H'] = Y - H
test['H-W1'] = H - W1
test['J-W1'] = J - W1
test['K-W1'] = K - W1
test['Y-W1'] = Y - W1
test['H-W2'] = H - W2
test['J-W2'] = J - W2

#Elegir sólo las columnas que se usaron para entrenar
X_test_final = test[features]

predictions = clf.predict(X_test_final)

test['Hclass'] = predictions

test.loc[:, ['Hclass']].to_csv('submit15.csv', index=True)

/tmp/ipykernel_4782/2537250058.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  test[problema] = test[problema].applymap(lambda x: np.nan if x <-30 or x>30 else x)
